/*==============================================================================================================================================
                                                        CONSTRUCTIONGLYPHS.CPP
==============================================================================================================================================*/
// 🧩 GENERATED by _ClaudeScratch/tmp/EmitConstructionGlyphs.py. PLACEHOLDER stage: one reference mark bound to every referenced key. All
//    keys carry identical bytes, so the registry's content-hash dedup uploads ONE texture. Keys ride Frontier::ResolveToolGlyphKey so the
//    reused ToolCard columns resolve them. ⚠️ Regenerate via the emitter; swap in the full translator for real art later.

#include "ConstructionGlyphs.h"

#include "EngineContext/Interface/Icons/IconPackToolMenu.h"
#include "EngineContext/Interface/Icons/SvgIconRegistry.h"

#include <cstdint>
#include <cstring>
#include <string>

namespace ConstructionCatalogueValidation
{

namespace
{
    // The supersampled master edge every construction glyph rasterizes at — the shared ToolCard master.
    constexpr uint32_t ConstructionGlyphMasterEdge = 64u;

    // 📝 The one reference mark, until the real S/D/F/O/B art is generated. A rounded square with a centred dot in --ink.
    const char* const ReferenceGlyphDocument =
        "<svg viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\">"
        "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"4\" fill=\"none\" stroke=\"#ececf0\" stroke-width=\"1.5\"/>"
        "<circle cx=\"12\" cy=\"12\" r=\"2\" fill=\"#ececf0\"/>"
        "</svg>";

    // Every tool/param glyph name the catalogue references, raw prototype identifiers (SolidBox, ParamWidth, …).
    const char* const ReferencedGlyphNames[] =
    {
        "AnnotateAngular",
        "AnnotateDiameter",
        "AnnotateLeader",
        "AnnotateLinear",
        "AnnotateOrdinate",
        "AnnotateRadial",
        "AnnotateSurfText",
        "AnnotateWeldMark",
        "BooleanCommonEdge",
        "BooleanCut",
        "BooleanFuseCompound",
        "BooleanGlue",
        "BooleanImprint",
        "BooleanIntersect",
        "BooleanSection",
        "BooleanSplit",
        "BooleanUnion",
        "CurveApproximate",
        "CurveArcTangent",
        "CurveBlend",
        "CurveBoundary",
        "CurveEdgeExtract",
        "CurveHelix",
        "CurveInterpolate",
        "CurveIntersect",
        "CurveIsoparam",
        "CurveLine3d",
        "CurveOffset",
        "CurveProject",
        "CurveSection",
        "CurveSpiral",
        "DataHeightfield",
        "DataImageTrace",
        "DataImportStep",
        "DataMeshConvert",
        "DataPointCloud",
        "DataProfileTable",
        "DataScanFit",
        "DataScriptSolid",
        "FramingCamera",
        "FramingEnvironment",
        "FramingTurntable",
        "LightArea",
        "LightPoint",
        "LightSpot",
        "LightSun",
        "ParamAngle",
        "ParamAxis",
        "ParamClosed",
        "ParamConstruction",
        "ParamCount",
        "ParamDepth",
        "ParamDirection",
        "ParamDistance",
        "ParamHeight",
        "ParamLink",
        "ParamMaterial",
        "ParamMirror",
        "ParamMode",
        "ParamOperand",
        "ParamPivot",
        "ParamPlane",
        "ParamRadius",
        "ParamRing",
        "ParamSeed",
        "ParamSmooth",
        "ParamSnap",
        "ParamStrength",
        "ParamTaper",
        "ParamThickness",
        "ParamTolerance",
        "ParamUnit",
        "ParamVisible",
        "ParamWidth",
        "PatternGrid",
        "PatternHelixPat",
        "PatternLinear",
        "PatternMirror",
        "PatternMove",
        "PatternPath",
        "PatternPolar",
        "PatternRotateCopy",
        "PatternScale",
        "PatternTransform",
        "RefAxis",
        "RefCoordSystem",
        "RefGridPlane",
        "RefLocalOrigin",
        "RefMidplane",
        "RefPlane",
        "RefPoint",
        "RefTangentPlane",
        "RefWorkplane",
        "SketchArc",
        "SketchArcThree",
        "SketchBezier",
        "SketchCentreRect",
        "SketchChamfer",
        "SketchCircle",
        "SketchCircleThree",
        "SketchConstruction",
        "SketchEllipse",
        "SketchExtend",
        "SketchFillet",
        "SketchLine",
        "SketchMirrorLine",
        "SketchOffset",
        "SketchPoint",
        "SketchPolygon",
        "SketchPolyline",
        "SketchProject",
        "SketchRectangle",
        "SketchSelect",
        "SketchSlot",
        "SketchSpline",
        "SketchTrim",
        "SolidBox",
        "SolidBoxCentre",
        "SolidBoxPoints",
        "SolidCapsule",
        "SolidCone",
        "SolidCylinder",
        "SolidEllipCyl",
        "SolidEllipsoid",
        "SolidHalfSpace",
        "SolidPolyhedron",
        "SolidPrism",
        "SolidPyramid",
        "SolidSphere",
        "SolidThicken",
        "SolidTorus",
        "SolidTruncCone",
        "SolidTube",
        "SolidWedge",
        "SurfaceBlendSurf",
        "SurfaceExtendSurf",
        "SurfaceExtrudeSurf",
        "SurfaceFill",
        "SurfaceLoftSurf",
        "SurfaceOffsetSurf",
        "SurfacePlanar",
        "SurfaceRevolveSurf",
        "SurfaceSewFaces",
        "SurfaceSweepSurf",
        "SurfaceTrimSurf",
        "SweepBoss",
        "SweepDraft",
        "SweepEvolve",
        "SweepHelical",
        "SweepLoft",
        "SweepPipe",
        "SweepPocket",
        "SweepPrism",
        "SweepRevolve",
        "SweepRuled",
        "SweepShellSolid",
        "SweepThickenFace",
    };

    // The seven dimension result badges.
    const char* const BadgeNames[] =
    {
        "Vertex",
        "Edge",
        "Wire",
        "Face",
        "Shell",
        "Solid",
        "Nothing",
    };
}

bool RegisterConstructionGlyphPack(Frontier::SvgIconRegistry& Registry)
{
    bool EveryGlyphRegistered = true;
    const uint32_t ByteCount = static_cast<uint32_t>(std::strlen(ReferenceGlyphDocument));

    for (const char* GlyphName : ReferencedGlyphNames)
    {
        if (!Frontier::RegisterSvgIcon(Registry, Frontier::ResolveToolGlyphKey(GlyphName, false),
                                       ReferenceGlyphDocument, ByteCount, ConstructionGlyphMasterEdge))
        {
            EveryGlyphRegistered = false;
        }
        if (!Frontier::RegisterSvgIcon(Registry, Frontier::ResolveToolGlyphKey(GlyphName, true),
                                       ReferenceGlyphDocument, ByteCount, ConstructionGlyphMasterEdge))
        {
            EveryGlyphRegistered = false;
        }
    }

    for (const char* BadgeName : BadgeNames)
    {
        std::string IconKey = "tool-badge-";
        IconKey += BadgeName;
        if (!Frontier::RegisterSvgIcon(Registry, IconKey, ReferenceGlyphDocument, ByteCount, ConstructionGlyphMasterEdge))
        {
            EveryGlyphRegistered = false;
        }
    }

    return EveryGlyphRegistered;
}

} // namespace ConstructionCatalogueValidation
