/*==============================================================================================================================================
                                                        CONSTRUCTIONGLYPHS.H
==============================================================================================================================================*/
// 🧩 The construction catalogue's icon pack. PLACEHOLDER stage — real per-op art is deferred, so every referenced tool, parameter and
//    badge key registers one neutral reference mark for now. GENERATED by _ClaudeScratch/tmp/EmitConstructionGlyphs.py from the set of
//    glyph names the catalogue references. 🔴 Registered under the SAME "tool-<name>" / "tool-badge-<name>" key namespace the shared
//    ToolCard leaves resolve through Frontier::ResolveToolGlyphKey, so the reused columns find a texture rather than the absent marker.
//    ⚠️ Re-run the emitter to regenerate; swap it for the full S/D/F/O/B translator to bring in the real art.

#pragma once
#ifndef FRONTIER_VALIDATION_CONSTRUCTIONCATALOGUE_CONSTRUCTIONGLYPHS_H
#define FRONTIER_VALIDATION_CONSTRUCTIONCATALOGUE_CONSTRUCTIONGLYPHS_H

namespace Frontier { struct SvgIconRegistry; }

namespace ConstructionCatalogueValidation
{

// Register the reference mark under every tool/param glyph key (live + gated) and every dimension-badge key. Returns false when any
// raster/upload failed. Call once after the registry is initialized, alongside the global pack.
bool RegisterConstructionGlyphPack(Frontier::SvgIconRegistry& Registry);

} // namespace ConstructionCatalogueValidation

#endif
